version: '3.9'
services:
  app:
    build: .
    container_name: fastapi
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:11-bullseye
    container_name: postgres
    ports:
      - "6500:5432"
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
  db-test:
    image: postgres:11-bullseye
    container_name: postgres-test
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - "6501:5432"

volumes:
  postgres-data: